---
title: "Day 3 activities"
author: "Sam Muir"
date: "2023-08-16"
output: html_document
---

```{r}
library(tidyverse )
```

```{r}
pm2_5 <- 48
```

```{r}
if (pm2_5 <  100) {
  print("Low to moderate risk")
} else if (100 <= pm2_5 & pm2_5 < 150) {
  print("Unhealthy for sensitive groups")
} else {
  print("Health risk present")
}
```

```{r}
species <- "blue whale"

if (str_detect(species, "whale")) {
  print("You found a whale!")
}
```

```{r}
base_burrito = 6.50
main_ingredient <- "chicken"

# if (str_detect(main_ingredient, "veggie")) {
#   print(base_burrito)
# } else if (str_detect(main_ingredient, "chicken")) {
#   print(base_burrito + 3) 
# } else if (str_detect(main_ingredient, "steak")) {
#   print(base_burrito + 3.25)
# }

switch(main_ingredient,
       "veggie" = print(base_burrito),
       "chicken" = print(base_burrito + 3),
       "steak" = print(base_burrito + 3.25))
```


```{r}
fish <- c(goldfish = 8, tetras = 10, guppies = 12, mollies =23)

for (i in seq_along(fish)) {
  prop_fish = fish[i] / sum(fish)
  print(prop_fish)
} 
```

```{r}
month.name

for (i in seq_along(month.name)) {
  print(paste(month.name[[i]], "is month", i))
}
```

